name: CI

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    name: Build ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip;
             pip install tensorflow;
             git clone https://github.com/N3PDF/madflow ~/madflow;
             cd ~/madflow;
             pip install .;

      - name: Compile
        run: make

      - name: Run the test
        run: make test
