name: CI

on:
  push:
  pull_request:

jobs:
  build-ubuntu:
    name: Build ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: python3 -m pip install --upgrade pip
             pip install tensorflow

      - name: Compile
        run: make
        
      - name: Run the tests
        run: make test
